// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpPKkfSHxS-vfvEDikE1mic0F5XYA3i2U',
    appId: '1:805839009328:web:21bff69323eedb12ae1ff5',
    messagingSenderId: '805839009328',
    projectId: 't-movie-4787b',
    authDomain: 't-movie-4787b.firebaseapp.com',
    storageBucket: 't-movie-4787b.appspot.com',
    measurementId: 'G-NLYHS3022D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk91c1eL9aYspOlDLKZYnsvltbzXxPGhc',
    appId: '1:805839009328:android:3d9519be4862e19bae1ff5',
    messagingSenderId: '805839009328',
    projectId: 't-movie-4787b',
    storageBucket: 't-movie-4787b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBobbsgUeLNoTjirXrzTR3BirexSMSMWno',
    appId: '1:805839009328:ios:175814021f464733ae1ff5',
    messagingSenderId: '805839009328',
    projectId: 't-movie-4787b',
    storageBucket: 't-movie-4787b.appspot.com',
    iosClientId: '805839009328-bupb2lpjmgpji6snb90et32rk46iqjtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieInfo',
  );
}
